### PR TITLE
[wakelock] Add wakelock_tizen package 

### PR DESCRIPTION
**Pull request by HakkyuKim**
Tizen support for [wakelock](https://github.com/creativecreatorormaybenot/wakelock) plugin.

To-Dos:
- [x] code formatting
- [x] testing on Tizen wearables
- [x] testing on Tizen TVs
- [x] implementing integration test
- [x] updating README in root

### CODE REVIEW

**Comment by swift-kim** [comment]
I see this error message whenever I click the buttons in the example app. Do you have any idea of why? I tested on my Galaxy Watch (R800) and the app itself just worked as expected.

```
E/ConsoleMessage(32699): Invalid read in StandardCodecByteStreamReader
E/ConsoleMessage(32699):
E/ConsoleMessage(32699): Invalid read in StandardCodecByteStreamReader
E/ConsoleMessage(32699):
E/ConsoleMessage(32699): Invalid read in StandardCodecByteStreamReader
E/ConsoleMessage(32699):
```

Also the runtime error message is not very clear to understand when the required privilege is not properly declared in `tizen-manifest.xml`. Can we make this any better?

```
E/ConsoleMessage( 2476): Thread added[0x8e2fc8, pid:2476 tid: 2476] to display:0x8ceac0, threads_cnt=1
E/ConsoleMessage( 2476): [ERROR:flutter/lib/ui/ui_dart_state.cc(186)] Unhandled Exception: NoSuchMethodError: Class 'bool' has no instance method '[]'.
E/ConsoleMessage( 2476): Receiver: true
E/ConsoleMessage( 2476): Tried calling: []("code")
E/ConsoleMessage( 2476): #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:54)
E/ConsoleMessage( 2476): #1      WakelockApi.toggle (package:wakelock_platform_interface/messages.dart:60)
E/ConsoleMessage( 2476): <asynchronous suspension>
E/ConsoleMessage( 2476): #2      MethodChannelWakelock.toggle (package:wakelock_platform_interface/method_channel_wakelock.dart:20)
E/ConsoleMessage( 2476): <asynchronous suspension>
E/ConsoleMessage( 2476):
```

The plugin logs:

```
D/WakelockTizenPlugin( 2476): wakelock_tizen_plugin.cc: RegisterWithRegistrar(14) > [WakelockTizenPlugin.RegisterWithRegistrar] Setting up channels.
D/WakelockTizenPlugin( 2476): wakelock_tizen_plugin.cc: operator()(41) > [WakelockTizenPlugin] Toggling wakelock status.
D/WakelockTizenPlugin( 2476): wakelock_tizen_plugin.cc: operator()(67) > [WakelockTizenPlugin] toggle to enable: true
E/WakelockTizenPlugin( 2476): wakelock_tizen_plugin.cc: operator()(77) > [WakelockTizenPlugin] toggling wakelock failed: Permission denied
```

**Review by pwasowski2 — COMMENTED** [review]
LGTM 👌

**Comment by HakkyuKim** [comment]
@swift-kim 

E/ConsoleMessage(32699): Invalid read in StandardCodecByteStreamReader
E/ConsoleMessage(32699):

This error happens when passing null to `BasicMessageChannel.send` in dart code (platform_interface). You can also see this error in [video_player_tizen](https://github.com/flutter-tizen/plugins/tree/master/packages/video_player). I believe the embedder is missing a certain null check step, I'll look more into it and submit a separate PR on this issue.

The error message wasn't sent correctly before, I fixed this in later commits.

**Review by swift-kim — APPROVED** [review]
Looks good to me!

**Pull request merged**
