### PR TITLE
[webview_flutter] Remove unused code

### PR DESCRIPTION
**Pull request by bbrto21**
* Remove unused code.
* Fix build warnings.

Signed-off-by: Boram Bae <boram21.bae@samsung.com>

### CODE REVIEW

**Comment by swift-kim** [comment]
Please reword the commit title. There's a typo.

**Comment by bbrto21** [comment]
> Please reword the commit title. There's a typo.

I changed the title.

**Review by swift-kim — APPROVED** [review]

**Comment by bwikbs** [comment]
One thing I'm worried about... as I remember... this handle is what we need for chromium-efl.

**Comment by bbrto21** [comment]
> One thing I'm worried about... as I remember... this handle is what we need for chromium-efl.

Are you worried about another webview made with `ewk`?
I have no plans to deprecate any Embedder APIs. I'm just cleaning up the unused code at here.

**Comment by bwikbs** [comment]
I guess.. it doesn't seem to matter....
I just thought that the structure of ewk and lwe should be as similar as possible... 
At this point, it seems meaningless anymore.

**Review by bwikbs — APPROVED** [review]
👍 Cool!

**Pull request merged**
