### PR TITLE
[network_info_plus] Handle wifi info retrieve failure case

### PR DESCRIPTION
**Pull request by HakkyuKim**
Fixes https://github.sec.samsung.net/f-project/home/issues/51 (internal repo).

### CODE REVIEW

**Review by seungsoo47 — APPROVED** [review]

**Review by bwikbs — APPROVED** [review]
GOOD!!!

**Comment by swift-kim** [comment]
Is this related to https://github.com/flutter-tizen/plugins/issues/273?

**Comment by HakkyuKim** [comment]
> Is this related to https://github.com/flutter-tizen/plugins/issues/273?

No its different but I am trying to solve both so I asked @wiertel for additional information.

**Comment by bbrto21** [comment]
published

**Comment by HakkyuKim** [comment]
@wiertel 
The PR has accidentally been merged early but I now believe #273 is actually the same issue, could you confirm this so we can close the issue?

**Pull request merged**
