### PR TITLE
[multi-packages]  Fix issues from static analysis

### PR DESCRIPTION
**Pull request by bwikbs**
Fix following issue:

* Missing break
* Uninitialized field
* Incorrect comparison

Signed-off-by: MuHong Byun <mh.byun@samsung.com>

### CODE REVIEW

**Review by HakkyuKim — APPROVED** [review]

**Comment by HakkyuKim** [comment]
In case of `webview_flutter`, I believe it should be published since it's a bug that affects functionality.

**Review by seungsoo47 — APPROVED** [review]

**Comment by swift-kim** [comment]
This PR was marked ready for review only 2 hours ago. You're too quick. @seungsoo47

**Comment by bwikbs** [comment]
@swift-kim 
It's kind of misunderstanding me and @seungsoo47 :cry:

**Comment by seungsoo47** [comment]
Oh. I am sorry. It's my mistake. @swift-kim

**Comment by bwikbs** [comment]
> In case of webview_flutter, I believe it should be published since it's a bug that affects functionality.

This will be done at #246.

**Pull request merged**
