### PR TITLE
[wifi_info_flutter] Add wifi_info_flutter_tizen package

### PR DESCRIPTION
**Pull request by bwikbs**

### CODE REVIEW

**Comment by bwikbs** [comment]
This package depends on the ``connectivity_tizen`` package.  So It should be merged after https://github.com/flutter-tizen/plugins/pull/29

**Comment by swift-kim** [comment]
Rebased the branch.

**Comment by swift-kim** [comment]
I'm going to add commits to this PR directly instead of adding reviews. Will it be fine with you? @bwikbs

**Review by swift-kim — APPROVED** [review]
LGTM

**Pull request merged**
