### PR TITLE
Use get_error_message() whenever possible

### PR DESCRIPTION
**Pull request by swift-kim**
- Avoid the error converter function and use `get_error_message()` instead.
- Use the new log.h template (`__FILE__` to `__MODULE__`).

### CODE REVIEW

**Review by bbrto21 — APPROVED** [review]
LGTM!  I feel comfortable after review this :smile:

**Review by rwalczyna — APPROVED** [review]
To get rid off condition when extracting file name, you can prepend `/` to `__FILE__`:

```cpp
#define __MODULE__ strrchr("/" __FILE__, '/') + 1
```
But it is not an issue and overall PR looks good to me.

**Comment by swift-kim** [comment]
@bbrto21 How do you think about @rwalczyna's suggestion? The current way is a bit more readable, but the suggested way looks simpler and cleaner.

**Comment by bbrto21** [comment]
I think @rwalczyna's suggestion looks better!
@swift-kim If you don't mind, could you update all macros of this PR and template of log.h ?

**Review by bwikbs — APPROVED** [review]
I didn't know that something like this ``get_error_message`` exist. 
I have been looking for a while where ``get_error_message`` is in your PR. :smile:

**Pull request merged**
