### PR TITLE
[WIP][video_player_plusplayer]Plusplayer plugin

### PR DESCRIPTION
**Pull request by xiaowei-guan**
Because MM player  is not in maintenance on TV device, and MM player not support DRM.
so we implement a new video player plugin based on plusplayer, it only supports tv devices.

### CODE REVIEW

**Comment by swift-kim** [comment]
- Please review your own code first (including README and other miscellaneous files).
- Read [the plugin submission guidelines](https://github.com/flutter-tizen/flutter-tizen/wiki/New-plugin-submission-guideline) and [the style guide](https://github.com/flutter-tizen/flutter-tizen/wiki/Style-guide).
- Provide any details that the reviewers and users might need, including design decisions you have made (what and why) and the current limitations of the plugin.

**Comment by xiaowei-guan** [comment]
> * Please review your own code first (including README and other miscellaneous files).
> * Read [the plugin submission guidelines](https://github.com/flutter-tizen/flutter-tizen/wiki/New-plugin-submission-guideline) and [the style guide](https://github.com/flutter-tizen/flutter-tizen/wiki/Style-guide).
> * Provide any details that the reviewers and users might need, including design decisions you have made (what and why) and the current limitations of the plugin.

Ok,  I just finished basic function and I will finish the rest.

**Comment by swift-kim** [comment]
The `_plus` suffix in the package name might confuse users as it's widely known as a naming convention for [plus plugins](https://plus.fluttercommunity.dev/docs/overview). Actually there's already a package with the name on [pub.dev](https://pub.dev/packages/video_player_plus) so we can't use that name.

If the name of the underlying platform API used by this plugin is "plusplayer", how about the name "video_player_plusplayer", similarly to [video_player_avfoundation](https://github.com/flutter/plugins/tree/main/packages/video_player/video_player_avfoundation) for iOS/macOS?

**Comment by xiaowei-guan** [comment]
> he `_plus` suffix in the package name might confuse users as it's widely known as a naming conv

Yes, you are right. I actually wanted to develop a video plugin based on official video player plugin from the beginning, but plusplayer does not support frame decode callback and API are not the same. In that case, "video_player_plusplayer" is a batter name. Thanks for your suggestion.

**Comment by NicolaVerbeeck** [comment]
When we try to stream a dash stream (with widevine) using this implementation, we are getting vague assertion fail messages from gstreamer. The same dash stream (without drm) plays just fine using the regular video_player package (which uses only methods from player.h as far as I can tell).

I tried to find documentation about the libdrmmanager but to no avail. Perhaps that samsung can provide us about how to link DRM with the player from player.h without resorting to this implementation which includes even more black boxes in the form of 2 SO files without any sources?

**Comment by xuelian-bai** [comment]
> When we try to stream a dash stream (with widevine) using this implementation, we are getting vague assertion fail messages from gstreamer. The same dash stream (without drm) plays just fine using the regular video_player package (which uses only methods from player.h as far as I can tell).
> 
> I tried to find documentation about the libdrmmanager but to no avail. Perhaps that samsung can provide us about how to link DRM with the player from player.h without resorting to this implementation which includes even more black boxes in the form of 2 SO files without any sources?

To play DRM with this streaming player, you need to have partner level certificate(https://developer.samsung.com/tv-seller-office/guides/membership/becoming-partner.html), if you already are partner, please send me mail(xuelian.bai@samsung.com),  I will send you USB certificate.

**Comment by NicolaVerbeeck** [comment]
If memory serves, even the non-drm stream fails with this package

**Comment by xuelian-bai** [comment]
@NicolaVerbeeck We will release another video player plugin with DRM(playready only) support, I will update  in this session when done.

**Comment by NicolaVerbeeck** [comment]
Nice! Looking forward to it!

**Comment by xuelian-bai** [comment]
We have another new player plugin which support DRM(playready,DASH+widevine) https://github.com/flutter-tizen/plugins/pull/468, so I will close this one.   @NicolaVerbeeck

**Pull request closed without merging**
