### PR TITLE
Workflows run test

### PR DESCRIPTION
**Pull request by HakkyuKim**
Test PR to verify integration tests with self-hosted runner. It will be closed after testing.

### CODE REVIEW

**Comment by bwikbs** [comment]
Finally!! :scream:

**Comment by HakkyuKim** [comment]
@swift-kim Integration test is failing for `tizen_app_control`. I'm not quite familiar with ffi, do I need to set something before running? This is the partial result of the test:

```
(The following exception is now available via WidgetTester.takeException:)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _CastError was thrown running a test:
type 'Null' is not a subtype of type 'bool' in type cast

When the exception was thrown, this was the stack:
#0      new ReceivedAppControl._fromMap (package:tizen_app_control/app_control.dart:225:42)
#1      AppControl.onAppControl.<anonymous closure> (package:tizen_app_control/app_control.dart:144:50)
(elided 22 frames from dart:async and package:stack_trace)
...

The test description was:
  Can receive request from platform
════════════════════════════════════════════════════════════════════════════════════════════════════
(If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following _CastError was thrown running a test:
type 'Null' is not a subtype of type 'bool' in type cast

When the exception was thrown, this was the stack:
#0      new ReceivedAppControl._fromMap (package:tizen_app_control/app_control.dart:225:42)
#1      AppControl.onAppControl.<anonymous closure> (package:tizen_app_control/app_control.dart:144:50)
(elided 22 frames from dart:async and package:stack_trace)
...

The test description was:
  Can receive request from platform
════════════════════════════════════════════════════════════════════════════════════════════════════
00:33 +0 -1: Can receive request from platform [E]                                                                                      
  Test failed. See exception logs above.
  The test description was: Can receive request from platform
  
00:33 +0 -1: Can send and receive request                                                                                               
(The following exception is now available via WidgetTester.takeException:)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following ArgumentError was thrown running a test:
Invalid argument(s): Failed to lookup symbol
(/opt/usr/globalapps/org.tizen.tizen_app_control_example/bin/../lib/libflutter_tizen_wearable.so:
undefined symbol: NativeInitializeDartApi)

When the exception was thrown, this was the stack:
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      _libEmbedder (package:tizen_app_control/src/ffi.dart)
#2      nativeCreateAppControl (package:tizen_app_control/src/ffi.dart:50:5)
#3      nativeCreateAppControl (package:tizen_app_control/src/ffi.dart)
#4      new AppControl (package:tizen_app_control/app_control.dart:73:11)
#5      main.<anonymous closure> (file:///home/hakkyu/mydir/project/flutter-project/plugins/packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart:31:32)
#6      main.<anonymous closure> (file:///home/hakkyu/mydir/project/flutter-project/plugins/packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart:29:47)
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:156:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  Can send and receive request
════════════════════════════════════════════════════════════════════════════════════════════════════
(If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the exception.)
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
The following ArgumentError was thrown running a test:
Invalid argument(s): Failed to lookup symbol
(/opt/usr/globalapps/org.tizen.tizen_app_control_example/bin/../lib/libflutter_tizen_wearable.so:
undefined symbol: NativeInitializeDartApi)

When the exception was thrown, this was the stack:
#0      DynamicLibrary.lookup (dart:ffi-patch/ffi_dynamic_library_patch.dart:31:29)
#1      _libEmbedder (package:tizen_app_control/src/ffi.dart)
#2      nativeCreateAppControl (package:tizen_app_control/src/ffi.dart:50:5)
#3      nativeCreateAppControl (package:tizen_app_control/src/ffi.dart)
#4      new AppControl (package:tizen_app_control/app_control.dart:73:11)
#5      main.<anonymous closure> (file:///home/hakkyu/mydir/project/flutter-project/plugins/packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart:31:32)
#6      main.<anonymous closure> (file:///home/hakkyu/mydir/project/flutter-project/plugins/packages/tizen_app_control/example/integration_test/tizen_app_control_test.dart:29:47)
#7      testWidgets.<anonymous closure>.<anonymous closure> (package:flutter_test/src/widget_tester.dart:156:29)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)
```

**Comment by swift-kim** [comment]
The engine containing relevant changes has not been released so the current latest version of flutter-tizen would not work.

**Comment by swift-kim** [comment]
I released a new engine today. Please test again when https://github.com/flutter-tizen/flutter-tizen/pull/235 lands.

**Comment by HakkyuKim** [comment]
I did build the latest engine and tested this morning but forgot that I was testing on an emulator;; built an arm version. Anyways thanks for the quick update.

**Comment by swift-kim** [comment]
The drive command works but the test command fails because the generated main generated by `commands/test.dart` is different from the one generated by `_createEntrypoint` in `tizen_plugins.dart`. (See https://github.com/flutter-tizen/flutter-tizen/pull/228.)

The problem will be eventually fixed when https://github.com/flutter-tizen/plugins/issues/123#issuecomment-888891157 is applied after the Flutter 2.5 migration but you can create a PR to apply https://github.com/flutter-tizen/flutter-tizen/pull/228 to `commands/test.dart`.

**Comment by HakkyuKim** [comment]
@swift-kim 
Ah, okay. Thanks for the help. I'll apply flutter-tizen/flutter-tizen#228 to `commands/test.dart` and try again.

**Comment by swift-kim** [comment]
The migration will happen very soon so you can also just exclude tizen_app_control from testing.

**Comment by HakkyuKim** [comment]
Closing after test.

**Comment by HakkyuKim** [comment]
Reopening to test #238.

**Comment by HakkyuKim** [comment]
Closing after test.

**Pull request closed without merging**
