### PR TITLE
[video_player] Update integration_test

### PR DESCRIPTION
**Pull request by XuWanchaoS**
- Update integration_test
- Update CHANGELOG.md and README.md
- Set paused after video completed.

### CODE REVIEW

**Review by swift-kim — APPROVED** [review]

**Review by bwikbs — APPROVED** [review]
I could't check test result because I am not in office, but I can't find a part that will be a issue!
Thanks!

**Comment by HakkyuKim** [comment]
@XuWanchaoS 
I see this error when running integration test on Tizen TV emulator, is this expected?

```sh
# Running: flutter-tizen drive --driver=test_driver/integration_test.dart --target=integration_test/video_player_test.dart
I/ConsoleMessage( 4466): flutter: 00:00 +0: asset videos can be initialized
E/ConsoleMessage( 4466): Invalid read in StandardCodecByteStreamReader
I/ConsoleMessage( 4466): flutter: 00:00 +1: asset videos reports buffering status
I/ConsoleMessage( 4466): flutter: 00:00 +1 ~1: asset videos live stream duration != 0
I/ConsoleMessage( 4466): flutter: 00:03 +2 ~1: asset videos can be played
I/ConsoleMessage( 4466): flutter: 00:04 +3 ~1: asset videos can seek
I/ConsoleMessage( 4466): flutter: 00:04 +4 ~1: asset videos can be paused
I/ConsoleMessage( 4466): flutter: 00:06 +5 ~1: asset videos stay paused when seeking after video completed
Failure in method: stay paused when seeking after video completed
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following TestFailure object was thrown running a test:
  Expected: <false>
  Actual: <true>

When the exception was thrown, this was the stack:
#4      main.<anonymous closure>.<anonymous closure> (file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart:161:9)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

This was caught by the test expectation on the following line:
  file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart line 161
The test description was:
  stay paused when seeking after video completed
═════════════════════════════════════════════════════════════════

end of failure 1



I/ConsoleMessage( 4466): flutter: (The following exception is now available via WidgetTester.takeException:)
I/ConsoleMessage( 4466): flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/ConsoleMessage( 4466): flutter: The following TestFailure object was thrown running a test:
I/ConsoleMessage( 4466): flutter:   Expected: <false>
I/ConsoleMessage( 4466): flutter:   Actual: <true>
I/ConsoleMessage( 4466): flutter: 
I/ConsoleMessage( 4466): flutter: When the exception was thrown, this was the stack:
I/ConsoleMessage( 4466): flutter: #4      main.<anonymous closure>.<anonymous closure>
(file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart:161:9)
I/ConsoleMessage( 4466): flutter: <asynchronous suspension>
I/ConsoleMessage( 4466): flutter: <asynchronous suspension>
I/ConsoleMessage( 4466): flutter: (elided one frame from package:stack_trace)
I/ConsoleMessage( 4466): flutter: ...
I/ConsoleMessage( 4466): flutter: 
I/ConsoleMessage( 4466): flutter: This was caught by the test expectation on the following line:
I/ConsoleMessage( 4466): flutter:   file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart line
161
I/ConsoleMessage( 4466): flutter: The test description was:
I/ConsoleMessage( 4466): flutter:   stay paused when seeking after video completed
I/ConsoleMessage( 4466): flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
I/ConsoleMessage( 4466): flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when
another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the
exception.)
I/ConsoleMessage( 4466): flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/ConsoleMessage( 4466): flutter: The following TestFailure object was thrown running a test:
I/ConsoleMessage( 4466): flutter:   Expected: <false>
I/ConsoleMessage( 4466): flutter:   Actual: <true>
I/ConsoleMessage( 4466): flutter: 
I/ConsoleMessage( 4466): flutter: When the exception was thrown, this was the stack:
I/ConsoleMessage( 4466): flutter: #4      main.<anonymous closure>.<anonymous closure>
(file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart:161:9)
I/ConsoleMessage( 4466): flutter: <asynchronous suspension>
I/ConsoleMessage( 4466): flutter: <asynchronous suspension>
I/ConsoleMessage( 4466): flutter: (elided one frame from package:stack_trace)
I/ConsoleMessage( 4466): flutter: ...
I/ConsoleMessage( 4466): flutter: 
I/ConsoleMessage( 4466): flutter: This was caught by the test expectation on the following line:
I/ConsoleMessage( 4466): flutter:   file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart line
161
I/ConsoleMessage( 4466): flutter: The test description was:
I/ConsoleMessage( 4466): flutter:   stay paused when seeking after video completed
I/ConsoleMessage( 4466): flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
I/ConsoleMessage( 4466): flutter: 00:08 +5 ~1: asset videos stay paused when seeking after video completed [E]
I/ConsoleMessage( 4466): flutter:   Test failed. See exception logs above.
I/ConsoleMessage( 4466):   The test description was: stay paused when seeking after video completed
I/ConsoleMessage( 4466): flutter:   
I/ConsoleMessage( 4466): flutter: 00:08 +5 ~1 -1: asset videos do not exceed duration on play after video completed
I/ConsoleMessage( 4466): flutter: (The following exception is now available via WidgetTester.takeException:)
I/ConsoleMessage( 4466): flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/ConsoleMessage( 4466): flutter: The following TestFailure object was thrown running a test:
I/ConsoleMessage( 4466): flutter:   Expected: <false>
I/ConsoleMessage( 4466): flutter:   Actual: <true>
I/ConsoleMessage( 4466): flutter: 
I/ConsoleMessage( 4466): flutter: When the exception was thrown, this was the stack:
I/ConsoleMessage( 4466): flutter: #4      main.<anonymous closure>.<anonymous closure>
(file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart:183:9)
I/ConsoleMessage( 4466): flutter: <asynchronous suspension>
I/ConsoleMessage( 4466): flutter: <asynchronous suspension>
I/ConsoleMessage( 4466): flutter: (elided one frame from package:stack_trace)
I/ConsoleMessage( 4466): flutter: ...
I/ConsoleMessage( 4466): flutter: 
I/ConsoleMessage( 4466): flutter: This was caught by the test expectation on the following line:
I/ConsoleMessage( 4466): flutter:   file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart line
183
I/ConsoleMessage( 4466): flutter: The test description was:
I/ConsoleMessage( 4466): flutter:   do not exceed duration on play after video completed
I/ConsoleMessage( 4466): flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
I/ConsoleMessage( 4466): flutter: (If WidgetTester.takeException is called, the above exception will be ignored. If it is not, then the above exception will be dumped when
another exception is caught by the framework or when the test ends, whichever happens first, and then the test will fail due to having not caught or expected the
exception.)
I/ConsoleMessage( 4466): flutter: ══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞════════════════════════════════════════════════════
I/ConsoleMessage( 4466): flutter: The following TestFailure object was thrown running a test:
I/ConsoleMessage( 4466): flutter:   Expected: <false>
I/ConsoleMessage( 4466): flutter:   Actual: <true>
I/ConsoleMessage( 4466): flutter: 
I/ConsoleMessage( 4466): flutter: When the exception was thrown, this was the stack:
I/ConsoleMessage( 4466): flutter: #4      main.<anonymous closure>.<anonymous closure>
(file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart:183:9)
I/ConsoleMessage( 4466): flutter: <asynchronous suspension>
I/ConsoleMessage( 4466): flutter: <asynchronous suspension>
I/ConsoleMessage( 4466): flutter: (elided one frame from package:stack_trace)
I/ConsoleMessage( 4466): flutter: ...
I/ConsoleMessage( 4466): flutter: 
I/ConsoleMessage( 4466): flutter: This was caught by the test expectation on the following line:
I/ConsoleMessage( 4466): flutter:   file:///home/hakkyu/mydir/project/flutter_tizen_dev/plugins/packages/video_player/example/integration_test/video_player_test.dart line
183
I/ConsoleMessage( 4466): flutter: The test description was:
I/ConsoleMessage( 4466): flutter:   do not exceed duration on play after video completed
I/ConsoleMessage( 4466): flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════
I/ConsoleMessage( 4466): flutter: 00:09 +5 ~1 -1: asset videos do not exceed duration on play after video completed [E]
I/ConsoleMessage( 4466): flutter:   Test failed. See exception logs above.
I/ConsoleMessage( 4466):   The test description was: do not exceed duration on play after video completed
I/ConsoleMessage( 4466): flutter:   
I/ConsoleMessage( 4466): flutter: 00:09 +5 ~1 -2: asset videos test video player view with local asset
I/ConsoleMessage( 4466): flutter: 00:09 +6 ~1 -2: (tearDownAll)
I/ConsoleMessage( 4466): flutter: 00:09 +7 ~1 -2: Some tests failed.
E/ConsoleMessage( 4466): embedder.cc (1815): 'FlutterEngineOnVsync' returned 'kInternalInconsistency'. Could not notify the running engine instance of a Vsync event.
E/ConsoleMessage( 4466): appcore: disconnect wl2_display
```

**Comment by XuWanchaoS** [comment]
The video_player plugin use mmplayer to play video on tizen platform, and there are many limitations on TV.
Please refert to https://github.com/flutter-tizen/plugins/tree/master/packages/video_player

I run integration test on mobile/watch emulator, all test case are passed.
But on TV emulator, the limitations caused some test cases failed.

**Comment by HakkyuKim** [comment]
Oh, I overlooked the limitation part. Thanks for explaining.

Just ran the test on 5.5 Wearable emulator again and got this error message:

```
Failure in method: do not exceed duration on play after video completed
══╡ EXCEPTION CAUGHT BY FLUTTER TEST FRAMEWORK ╞═════════════════
The following PlatformException was thrown running a test:
PlatformException(player_start failed, Function not implemented,
null, null)

When the exception was thrown, this was the stack:
#0      VideoPlayerApi.play (package:video_player_platform_interface/messages.dart:315:7)
<asynchronous suspension>
<asynchronous suspension>
(elided one frame from package:stack_trace)

The test description was:
  do not exceed duration on play after video completed
═════════════════════════════════════════════════════════════════

end of failure 1
```

It's kind of strange cuz I remember running it earlier this morning and it passed. The error message looks similar to https://github.com/flutter-tizen/plugins/issues/135, is it a memory issue?

**Comment by XuWanchaoS** [comment]
yes, and if you just test this one case, it will be passed.

**Comment by HakkyuKim** [comment]
I actually did run this one case, even tried after restarting the emulator. But I see it's not solvable at this point.

**Comment by XuWanchaoS** [comment]
> 
> 
> I actually did run this one case, even tried after restarting the emulator. But I see it's not solvable at this point.

I test 'do not exceed duration on play after video completed' case on  5.5 Wearable emulator, it's passed without any error.
Could you share more infomation?

**Comment by HakkyuKim** [comment]
I just created a wearable 5.5 emulator with the default options and ran the integration test with the following command in the example directory:

```
flutter-tizen drive --driver=test_driver/integration_test.dart --target=integration_test/video_player_test.dart
```

I'm not sure these will help, but I'll attach the emulator conf files:

- [vm_config.txt](https://github.com/flutter-tizen/plugins/files/6860939/vm_config.txt)
- [vm_launch.txt](https://github.com/flutter-tizen/plugins/files/6860940/vm_launch.txt)

I had to change the file names cuz Github didn't allow uploading with the original extension name:

- vm_config.xml -> vm_config.txt
- vm_launch.conf -> vm_launch.txt

**Comment by XuWanchaoS** [comment]
The issue is caused by memory limit of muse-server (/usr/lib/systemd/system/muse-server.service), and restart or create new emulator can't fix it.

I mean you can enable half test case of video_player_test.dart to test first, then test others.

**Review by HakkyuKim — APPROVED** [review]
I've tested on a real target and an emulator on my office PC and confirmed that all test cases pass(@XuWanchaoS Even 'live stream duration != 0' on an emulator without configuring any Wi-Fi settings). The issue seems to be with the emulator running on my home PC.

**Pull request merged**
