### PR TITLE
Update tizen-manifest.xml files

### PR DESCRIPTION
**Pull request by swift-kim**
- Change the organization prefix in package and application IDs (`com.example` → `org.tizen`).
- Remove unnecessary `api-version` attributes from `ui-application` elements.
- Remove unnecessary `tv-info` elements.

### CODE REVIEW

**Comment by bbrto21** [comment]
There is old package name at `tizen_app_manager/example/lib/main.dart`
```dart
  late AppRunningContext _currentAppContext =
      AppRunningContext(appId: 'com.example.tizen_app_manager_example');
```

**Comment by HakkyuKim** [comment]
Some missing changes!

- `com.example` -> `org.tizen`
    - `tizen_app_manager/example/lib/main.dart`
    - `tizen_app_control/README.md` ?

- Removing `api-version`
    - `google_maps_flutter/example/tizen/tizen-manifest.xml`
    - `webview_flutter_tizen/example/tizen/tizen-manifest.xml`

**Comment by swift-kim** [comment]
Oops. I just used this command and there were some exceptional cases.

```sh
sed -i 's/ api-version="4">/>/g' packages/*/example/tizen/tizen-manifest.xml
```

**Review by HakkyuKim — APPROVED** [review]
LGTM

**Review by bbrto21 — APPROVED** [review]

**Pull request merged**
