### PR TITLE
Change method name's first letter

### PR DESCRIPTION
**Pull request by seungsoo47**
* According to convention, I change the method name's the first letter from lower case to upper case.

### CODE REVIEW

**Comment by bwikbs** [comment]
Now, Are we satisfied with coding style through this ❓ (Is there anything left?)
BTW, Where can I find the rules regarding this?

**Review by bwikbs — APPROVED** [review]

**Comment by seungsoo47** [comment]
https://github.com/flutter-tizen/engine/pull/14#pullrequestreview-556763316
I referred to a comment of @bbrto21 .

**Comment by bbrto21** [comment]
> Now, Are we satisfied with coding style through this  (Is there anything left?)
> BTW, Where can I find the rules regarding this?

We've been using Google styles since we started this project internally. This is from the flutter project [contributing guide](https://github.com/flutter/engine/blob/master/CONTRIBUTING.md)

**Comment by bbrto21** [comment]
We don't have a CI for tidy, so I'd like to avoid mentioning coding styles in the review as much as possible.

**Review by bbrto21 — APPROVED** [review]
LGTM

**Pull request merged**
