### PR TITLE
[firebase_core] Add firebase_core_tizen

### PR DESCRIPTION
**Pull request by HakkyuKim**
The `firebase_core` package is the required package to use all other Flutterfire plugins.

Contributes to https://github.com/flutter-tizen/flutter-tizen/issues/353.

Code in `firebase_core_tizen.dart` and `firebase_app_tizen.dart` are copied from https://github.com/invertase/flutterfire_desktop/tree/main/packages/firebase_core/firebase_core_desktop/lib with some minor changes. Ideally the package could be implemented with just a simple wrapper class that delegates all methods to [FirebaseCore](https://github.com/invertase/flutterfire_desktop/blob/547ec08286e557e973f797ad5f1eba37eacc895f/packages/firebase_core/firebase_core_desktop/lib/firebase_core_desktop.dart#L14), but in this case `firebase_core_tizen` cannot import classes from `firebase_core_desktop.dart` because of the `part`/`part of` directive: https://dart.dev/tools/diagnostic-messages?utm_source=dartdev&utm_medium=redir&utm_id=diagcode&utm_content=import_of_non_library#import_of_non_library.

For `FirebaseOptions`, you can add either Android or iOS app in the Firebase project and use its appId, apiKey, etc.

### CODE REVIEW

**Comment by swift-kim** [comment]
If there's no Tizen-specific code in this package, can you just directly contribute to their repo and use the "_dekstop" package as it is? Are we going to create "_tizen" versions of all the "_desktop" packages?

**Comment by HakkyuKim** [comment]
It could be possible, if the accept our contribution.

And we would have to make some fixes in the flutter-tizen tool side; changing the dart plugin registering method `register` to `registerWith`.

**Comment by swift-kim** [comment]
Ah, the platform declaration part in `pubspec.yaml`. That's actually Tizen-specific code. It'd be better to have all our code in this repo I think.

**Comment by HakkyuKim** [comment]
Firebase plugins were already being developed here: [www.github.sec.samsung.net/RP07-TIZEN/flutterfire_desktop](https://github.sec.samsung.net/RPO7-TIZEN/flutterfire_desktop) (internal repo).

I'll discuss with the SRPOL developer on how to proceed with firebase and close this PR.

**Comment by HakkyuKim** [comment]
Closing in favor of #476.

**Pull request closed without merging**
