### PR TITLE
Update copyright information

### PR DESCRIPTION
**Pull request by swift-kim**
- Add missing copyright info.
- Format the LICENSE files consistently.
- Always use the BSD-3 license for our source code. If the example app is licensed under another license, use that license for the example package only (e.g. audioplayers, flutter_tts, geolocator).

### CODE REVIEW

**Comment by JSUYA** [comment]
> `Copyright 2021 Samsung Electronics Co `

How about updating 2021 to 2022?
or, you can also write like this: "2021 - 2022"

**Comment by swift-kim** [comment]
@JSUYA The year represents the year the file or package was created. We all agreed on this detailed format when we were open-sourcing this project back in 2020. Please discuss with @haesik if you're to make an update. :)

**Comment by HakkyuKim** [comment]
Just one missed in `image_resize.h`.

**Comment by HakkyuKim** [comment]
Just one missed in `image_resize.h`.

**Comment by swift-kim** [comment]
> Just one missed in `image_resize.h`.

Nice catch!

**Review by HakkyuKim — APPROVED** [review]
LGTM!

**Pull request merged**
